# Generated by Django 4.2.25 on 2025-12-26 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دوره')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('thumbnail', models.ImageField(upload_to='courses/thumbnails/', verbose_name='تصویر کاور')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='مقطع تحصیلی')),
                ('subject', models.CharField(max_length=100, verbose_name='نام درس')),
                ('is_published', models.BooleanField(default=True, verbose_name='وضعیت انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL, verbose_name='شرکت\u200cکنندگان')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to='accounts.teacher', verbose_name='مدرس اصلی')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان ویدیو')),
                ('video_file', models.FileField(upload_to='courses/videos/', verbose_name='فایل ویدیو')),
                ('duration', models.CharField(max_length=10, verbose_name='مدت زمان')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.course', verbose_name='دوره')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
