# Generated by Django 4.2.25 on 2025-12-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_type_course_handout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(default='00:00', editable=False, max_length=20),
        ),
    ]
